### ISSUE TITLE
Wrong service provider mentioned in the documentation

### ISSUE THREAD

**Issue by apps-in-progress** [lucidarch/lucid#16]
In the service structure example under the "Concept -> Services" you defined the wrong service provider. Instead of KitchenServiceProvider, you should define ForumServiceProvider.

     app/Services/Forum
    ├── Console
    │   └── Commands
    ├── Features
    ├── Operations
    ├── Http
    │   ├── Controllers
    │   └── Middleware
    ├── Providers
    │   ├── KitchenServiceProvider <- should be ForumServiceProvider
    ...

---

Under the "Concept -> Organization -> Last point" there is a duplicated phrase "yet reside".

---
 
There is a typo under the "Concept -> Boundaries". Word "proetcting" should become "protecting".

**Comment by Mulkave** [comment]
thank you for reporting these! They've been fixed now 👍
