### ISSUE TITLE
automate command to create test templates for monolith services

### ISSUE THREAD

**Issue by khanzadimahdi** [lucidarch/lucid#20]
how can i create test files for a monolith service using CLI ?

**Comment by Batisska** [comment]
[Commands](https://docs.lucidarch.dev/cli/#commands)

![Screenshot from 2021-04-22 17-42-57](https://user-images.githubusercontent.com/17672321/115734480-6893c700-a392-11eb-8f3f-2c1181f731c0.png)

**Comment by khanzadimahdi** [comment]
so we have lack of the below commands:

1- CLI command to create Feature and Unit tests.
2- CLI command to create components (view component I mean).

**Comment by Mulkave** [comment]
@khanzadimahdi
1. Feature and unit tests are automatically created once you've created a feature through CLI as mentioned in [the docs](https://docs.lucidarch.dev/features/#generate-feature-class)
<img width="854" alt="Screenshot 2021-05-05 at 12 30 29 PM" src="https://user-images.githubusercontent.com/2647333/117121730-af73ba80-ad9d-11eb-9cd9-4bbc8ac33b06.png">

2. Yes indeed this command is missing. Would love to collaborate on a PR if you're interested
