### ISSUE TITLE
How to handle a feature that has related jobs

### ISSUE THREAD

**Issue by yanielbf** [lucidarch/lucid#25]
The architecture seems incredible to me. I'm going to start using it. Thanks for the input. After reading the documentation I have doubts in relation to the characteristics. I am on the example of creating an article. I want to divide the process of creating an article into 4 jobs:
1. Validate data
2. Upload image to an amazon bucket
3. Save the post
4. Return the answer

Suppose that step 1 and 2 are executed worse when reaching three an error occurs, you would have to make a rollback of step 2 and delete the uploaded file.

Question 1: Would I have to make a job run if one of these steps cannot be created, something like DeleteImageJob?
Question 2: How would you execute an Eloquent transaction in this process?

Again, congratulations on the job. Greetings

**Comment by Batisska** [comment]
With validation, everything seems to be clear. We use standard feature requests. We also send the answer to the task.

2 and 3 I most likely put the task in the job.

Saving and loading the image should be put in an operation and use the interface ShouldQueue.

In my humble opinion.
