### ISSUE TITLE
Factories / Seeders in Service deprecated?

### ISSUE THREAD

**Issue by mwkohler** [lucidarch/lucid#26]
Is it deprecated to make factories and seeders in services?
There's no command for making them for a service and since factories and seeders have namespaces now, it would require registering them in the service's provider which is ALSO not being done.

I feel like it should be properly decided and updated whether services should have separate database folders or share the laravel project's and maybe just have folders there.

**Comment by Batisska** [comment]
I am currently using standard seeds and factories. 
It seems to me that the standard ones are convenient. Since the models in the domains are still the same and will also be used
