### ISSUE TITLE
Catch Exceptions in Jobs

### ISSUE THREAD

**Issue by cayaner** [lucidarch/lucid#35]
We cannot catch exceptions in jobs:

![Screenshot 2021-11-03 120523](https://user-images.githubusercontent.com/19613212/140033663-71ccf00c-4129-4d90-b712-322d3c493a90.jpg)

**Comment by Mulkave** [comment]
That's an IDE thing, if an exception was thrown from within `GetUserByIdentifierJob`, `LoginUserOperation` would still catch it, but the IDE doesn't know about it.

There is a plan to introduce an IntelliJ (PHPStorm) plugin that would solve these issues, it would also get the return type of the called unit (i.e. `$user` will be what the job will return and you'd be able to use autocomplete properly in your IDE).

Sorry for the inconvenience.

If you happen to know anything about writing IDE plugins, any help would be appreciated!
