### ISSUE TITLE
Laravel 9 Support?

### ISSUE THREAD

**Issue by ThaDaVos** [lucidarch/lucid#37]
I haven't tried it yet, but is it confirmed that Lucid supports Laravel 9 yet?

**Comment by eschricker** [comment]
@ThaDaVos have you tested it yet?

**Comment by ThaDaVos** [comment]
It luckily seems to work, haven't run into any issues yet

**Comment by eschricker** [comment]
Cool, thanks for you quick reply :)

**Comment by Mulkave** [comment]
Yes, so far no issues here too! ✌️
